CREATE DATABASE IF NOT exists ROCKET1;
USE ROCKET1;

CREATE TABLE USUARIOS (
	ID INT(11) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(45) DEFAULT NULL,
    SEGUNDONOMBRE VARCHAR(45) DEFAULT NULL,
    APELLIDOPATERNO VARCHAR(45) DEFAULT NULL,
    APELLIDOMATERNO VARCHAR(45) DEFAULT NULL,
    FECHADENACIMIENTO VARCHAR(45) DEFAULT NULL,
    EMAIL VARCHAR(45) DEFAULT NULL,
    TELEFONO VARCHAR(10) DEFAULT NULL,
    PRIMARY KEY(ID)
);
DESCRIBE USUARIOS;
