CREATE DEFINER=`root`@`localhost` PROCEDURE `USUARIOADDOREDIT`(
	IN _ID INT(11),
    IN _NOMBRE VARCHAR(45),
    IN _SEGUNDONOMBRE VARCHAR(45),
    IN _APELLIDOPATERNO VARCHAR(45),
    IN _APELLIDOMATERNO VARCHAR(45),
    IN _FECHADENACIMIENTO VARCHAR(45) ,
    IN _EMAIL VARCHAR(45) ,
    IN _TELEFONO VARCHAR(10) 
)
BEGIN
	IF _ID=0 THEN
		INSERT INTO usuarios (NOMBRE, SEGUNDONOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,FECHADENACIMIENTO,EMAIL,TELEFONO)
		VALUES(_NOMBRE, _SEGUNDONOMBRE,_APELLIDOPATERNO,_APELLIDOMATERNO,_FECHADENACIMIENTO,_EMAIL,_TELEFONO);
		SET _ID = LAST_INSERT_ID();
	ELSE
		UPDATE usuarios	
        SET 
			NOMBRE=_NOMBRE,
            SEGUNDONOMBRE=_SEGUNDONOMBRE,
            APELLIDOPATERNO=_APELLIDOPATERNO,
            APELLIDOMATERNO=_APELLIDOMATERNO,
            FECHADENACIMIENTO=_FECHADENACIMIENTO,
            EMAIL=_EMAIL,
            TELEFONO=_TELEFONO
            WHERE ID = _ID;
	END IF;
    
    SELECT _ID AS ID;
        
END